### ISSUE TITLE
Towncrier imposes workflow challenges

### ISSUE THREAD

**Issue by jaraco** [hawkowl/towncrier#117]
In many of my projects, I have a zero-impedance release workflow - tag a commit and push produces a new release. This workflow often means I can accept a PR and cut a release with that functionality without leaving GitHub, especially if I can get the contributor to provide a changelog entry. Having something like Towncrier would help with this, except that it requires an intermediate manual step to produce the news from the fragments. That step requires that the version that's about to be tagged be known.

Is there any way to use Towncrier in this workflow?

One possibility I imagine is a tagged commit could trigger towncrier; if it finds fragments, it consumes them, commits the changes, and then force re-tags; if it doesn't find fragments, it does nothing.

Another option might be for Towncrier to leave the newsfragments unconsumed, and when invoked, produce the entire news file, grouping the results into releases based on the first (version) tag in which each fragment appears. In this model, towncrier could be invoked before generating docs, producing the NEWS file just in time for publishing (and package release).

**Comment by mauritsvanrees** [comment]
I wonder if [zest.releaser](http://zestreleaser.readthedocs.io/en/latest/) installed in combination with plugin [zestreleaser.towncrier](https://pypi.org/project/zestreleaser.towncrier/) would fit your usecase. Calling `fullrelease` would update the `setup.py` version and use `towncrier` to update the changelog file with that same version, and upload the result to PyPI. Use `fullrelease --no-input` if you want to accept the default answers to questions that `zest.releaser` asks.

I don't see how you could trigger this without leaving github though.

**Comment by stephenfin** [comment]
You could also look at [reno](https://github.com/openstack/reno), which using git tags to map a release note to a given release.

**Comment by jaraco** [comment]
Reno is a _really close fit_ for what I'm trying to achive. Thanks for that reference.

And I agree, better to have two tools to handle the nuances of the two workflows.
