### ISSUE TITLE
Could there be a new news fragment for major changes such as `.major`?

### ISSUE THREAD

**Issue by acabarbaye** [hawkowl/towncrier#132]
It sometimes happens that significant refactoring or architecture changes should be described or treated differently than newly introduced features. Therefore, could there be a new news fragment for such changes like `.major` or so and which would have a different section in the Changelog?

**Comment by Sup3rGeo** [comment]
I was doing my research for a good way of automatically dealing with versioning and it seems that having this `.major` would allow to define semantic versioning automatically from the news.

Although I am not sure if `major` would be the best name for it:

Qualitative description: semantic versioning item
- bugfix: patch
- new, backward compatible feature: minor
- incompatible changes: major

So it could be called maybe `incompatible`, or something better (but still a qualitative description, following the logic of the table).

**Comment by acabarbaye** [comment]
@Sup3rGeo : This project is doing exactly what you mention about automatic semantic versioning based on news files: https://github.com/ARMmbed/autoversion. However, as you mention, a news file describing `major` changes responsible for `major` version bump is needed to be fully complete.

**Comment by hawkowl** [comment]
You can define custom fragments using the `toml` config: https://github.com/hawkowl/towncrier#further-options
