### ISSUE TITLE
Add `--config` option to avoid pip+pyproject.toml interaction

### ISSUE THREAD

**Issue by davidism** [hawkowl/towncrier#148]
Pip is currently working out their PEP 517 support, which is triggered based on the presence of the `pyproject.toml` file. Some projects, such as Pallets, want to avoid this behavior until things are more stable. To facilitate that, let's add a `--config towncrier.toml` option to point to an alternative config. This would not introduce a new config format, it would still be TOML under the `[tool.towncrier]` key. Possibly, `.towncrier.toml` and `towncrier.toml` could be autodetected like `pyproject.toml`.

**Comment by webknjaz** [comment]
@davidism there's currently `--pyproject other. pyproject.toml`. I saw it in some pip-related issues and in code. So this request should be converted into a documentation improvement.

**Comment by seberg** [comment]
@webknjaz can you explain that?  I see it for `towncrier.check`, but not for the main incarnation. This is currently also a show stopper for numpy in my opinion, and we really wanted to try this out for the next release cycle starting pretty much now.

**Comment by webknjaz** [comment]
What you mean?

**Comment by seberg** [comment]
Well, we actually solved it now by just embracing `pyproject.toml` a bit more. The thing is that if you have a `pyproject.toml` pip works differently, and this difference can easily break on slightly more complex install processes.

**Comment by webknjaz** [comment]
I know. But you can use a custom name for the config which would fix that.

**Comment by seberg** [comment]
@webknjaz no, that part does not work, at least I cannot see any place to do that in towncrier master (except for `python -m towncrier.test` which I do not think is the right thing).

**Comment by webknjaz** [comment]
What do you mean by saying that you don't some place?

**Comment by seberg** [comment]
I mean that I tried to pass in a towncrier.toml, or similar and only for `towncrier.test` it seems implemented and I am not even sure what that does, but it does not do everything.

**Comment by webknjaz** [comment]
This is what I saw: https://github.com/hawkowl/towncrier/blob/47754a607a9b03f06affaf167d65b990786aae25/src/towncrier/check.py#L29

**Comment by hawkowl** [comment]
`--config` is now implemented on master.
