### ISSUE TITLE
No __version__ Exception unhelpful message

### ISSUE THREAD

**Issue by johnwlockwood** [hawkowl/towncrier#3]
My package `__init__.py` has `__version__` defined, but towncrier throws the No __version__ Exception. It doesn't make it clear if I have the towncrier.ini configured to the wrong place or if it's some other issue. How does towncrier read the version without loading the module?

**Comment by hawkowl** [comment]
Hmm, it does import the module -- it adds ``package_dir`` to ``sys.path``, imports it, and then looks for ``<yourpackage>.__version__``.

Is your setup somewhere public where I can see? :)

**Comment by johnwlockwood** [comment]
Sure, It is at https://github.com/johnwlockwood/txnats. While the whole thing isn't Python3 compatible, the package init can be loaded and it's __version__ can be read.

**Comment by hawkowl** [comment]
Ah, I see! Your ``__version__`` isn't a string or an Incremental ``Version()``, but a tuple -- towncrier currently only supports those two.. Supporting that seems easy enough, I'll add it :)
