### ISSUE TITLE
Title format produces wrong sized header

### ISSUE THREAD

**Issue by dstufft** [hawkowl/towncrier#46]
Currently the title format is ``{name} {version}\n==========\n``, which is fine except it ends up producing something that looks like:

```
MyProject 3.7.0a1
==========
```

It would be nice if there was a way to do this nicer, perhaps a ``title_template``? Or maybe by passing ``name``, ``version``, and ``project_date`` into the template and letting people set ``title_template = False`` and take full control of the title display inside the template?

**Comment by hawkowl** [comment]
Fixed in #50, the title format should be controllable (set to a null string should work? needs tests :))
