### ISSUE TITLE
Line wrapping should be optional

### ISSUE THREAD

**Issue by hynek** [hawkowl/towncrier#80]
If you use MD or rST, line wrapping doesn't make a lot of sense.  It would be nice if I could disable it with an option.

**Comment by wcooley** [comment]
👍  for disabling line-wrapping. I tend to write lots of nested lists to reduce the "big wall of text that no one reads" to the "big list of text that no one reads" and the line wrapping does not permit that. 

For example, I might have an issue to remove bits of an API in a project that is mainly developer oriented, so I would like to actually enumerate the identifiers that are being removed. Doing so in a single paragraph becomes unreadable very quickly.

That said, I also am not sure how it would work with automatically including the issue ID and URL, at least, not how this is done currently.

**Comment by hynek** [comment]
Since I’ve just caught myself procrastinating on an attrs release because I didn’t want to fix the layout by hand again, I fixed it in an private fork: https://github.com/hynek/towncrier/tree/no-reflow – (it’ll need a tweaked template too: https://github.com/python-attrs/attrs/blob/master/towncrier_template.rst – configurable [here](https://github.com/python-attrs/attrs/blob/bf159b30df2fc3e443d9313226328437ca2c6aa2/pyproject.toml#L5).)

Maybe it’s useful to others too until we get a proper fix.

**Comment by hawkowl** [comment]
In master, now, I'll do a RC to test today.

**Comment by hynek** [comment]
yeah this has been fixed
