### ISSUE TITLE
Read config from setup.cfg instead of pyproject.toml

### ISSUE THREAD

**Issue by htgoebel** [hawkowl/towncrier#81]
pyproject.toml is just an .ini.file – but yet another one. Python project often already have a  `setup.cfg` file, which in an .ini-file, too.

Please make towncrier read the config from setup.cfg instead of pyproject.toml. zest.releaser and py.test already do this. This would reduce the number of files polluting the top-level directory. A typical project already has quite some of these file and every one more is a burden. (Esp. since this file is not a hidden file on posix systems)

**Comment by hawkowl** [comment]
`pyproject.toml` is toml, which is a bit nicer than INI, and is defined in https://www.python.org/dev/peps/pep-0518/ as a place where "tool config" lives. Ideally, those projects will move to pyproject.toml too, as co-opting setup.cfg is a bit of a hack :)

However, I am considering a `.towncrier.toml`, which would be better for non-Python projects...

**Comment by htgoebel** [comment]
Thanks for pointing to PEP 518, I did not know it yet.
