### ISSUE TITLE
Newsfragment removal fails for files with extra extensions

### ISSUE THREAD

**Issue by njsmith** [hawkowl/towncrier#99]
In #65, I made towncrier ignore extensions on newsfragment filenames, so that you could use names like `newsfragments/17.feature.rst` and your editor would understand this was a `.rst` file.

Apparently I missed a case, because when you use towncrier in for-real-release-mode, it currently sees the above file, moves it into your release notes, and then tries to remove `newsfragments/17.feature`, which fails because that's not what the file is called:

```
~/trio$ towncrier
Loading template...
Finding news fragments...
Rendering news fragments...
Writing to newsfile...
Staging newsfile...
Removing news fragments...
I want to remove the following files:
/home/njs/trio/newsfragments/1.removal
/home/njs/trio/newsfragments/1.removal
/home/njs/trio/newsfragments/241.removal
/home/njs/trio/newsfragments/241.removal
/home/njs/trio/newsfragments/377.removal
/home/njs/trio/newsfragments/377.removal
/home/njs/trio/newsfragments/136.feature
/home/njs/trio/newsfragments/377.feature
/home/njs/trio/newsfragments/136.feature
/home/njs/trio/newsfragments/277.bugfix
/home/njs/trio/newsfragments/277.bugfix
Is it okay if I remove those files? [Y/n]: 
fatal: pathspec '/home/njs/trio/newsfragments/1.removal' did not match any files
Done!
```

**Comment by obestwalter** [comment]
Just stumbled over this while trying make a release and made the simplest possible fix I could come up with.
